"""
Generate qr_sjt_data.sql from the two Excel files.
Run: python3 supabase/generate_data_sql.py
Output: supabase/qr_sjt_data.sql  (paste into Supabase SQL editor)
"""

import openpyxl, re, os

QR_FILE  = os.path.expanduser("~/Downloads/UCAT_QR_Complete_Question_Bank_Corrected.xlsx")
SJT_FILE = os.path.expanduser("~/Downloads/UCAT_SJT_Complete_Question_Bank_Expanded.xlsx")
OUT_FILE = os.path.join(os.path.dirname(__file__), "qr_sjt_data.sql")

def esc(v):
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

def letter_to_idx(letter):
    """'A' → 0, 'B' → 1, etc."""
    m = re.search(r'\b([A-E])\b', str(letter).upper())
    return ord(m.group(1)) - ord('A') if m else 0

lines = []
lines.append("-- Auto-generated by generate_data_sql.py — do not edit by hand")
lines.append("-- Run AFTER qr_sjt_migration.sql\n")

# ═══════════════════════════════════════════════════════════════════
# QR
# ═══════════════════════════════════════════════════════════════════
print("Reading QR data …")
wb = openpyxl.load_workbook(QR_FILE, read_only=True)

lines.append("-- ─── QR datasets ───────────────────────────────────────────────────────────")

seen_datasets = {}  # dataset_id → True

def process_qr_sheet(ws, sheet_name):
    rows = list(ws.iter_rows(values_only=True))
    # header row is always row index 3
    data = [r for r in rows[4:] if r[0] and isinstance(r[0], str) and '-Q' in str(r[0])]
    for r in data:
        q_id      = r[0]
        level     = r[1]   # Bronze / Silver / Gold
        topic     = r[2] or ''
        ds_id     = r[3]
        ds_title  = r[4] or ''
        fig_brief = r[5] or ''
        scenario  = r[6] or ''
        question  = r[7] or ''
        opt_a     = r[8] or ''
        opt_b     = r[9] or ''
        opt_c     = r[10] or ''
        opt_d     = r[11] or ''
        opt_e     = r[12] or ''
        correct   = r[13] or ''
        walkthru  = r[14] or ''
        skill     = r[15] or ''
        time_sec  = int(r[16]) if r[16] and str(r[16]).isdigit() else 45

        if ds_id not in seen_datasets:
            seen_datasets[ds_id] = True
            lines.append(
                f"INSERT INTO qr_datasets (id, title, figure_brief, scenario) VALUES "
                f"({esc(ds_id)}, {esc(ds_title)}, {esc(fig_brief)}, {esc(scenario)}) "
                f"ON CONFLICT (id) DO NOTHING;"
            )

        lines.append(
            f"INSERT INTO qr_questions "
            f"(id, dataset_id, difficulty, topic, question, option_a, option_b, option_c, option_d, option_e, "
            f"correct_answer, walkthrough, skill_tested, time_sec) VALUES "
            f"({esc(q_id)}, {esc(ds_id)}, {esc(level)}, {esc(topic)}, {esc(question)}, "
            f"{esc(opt_a)}, {esc(opt_b)}, {esc(opt_c)}, {esc(opt_d)}, {esc(opt_e)}, "
            f"{esc(correct)}, {esc(walkthru)}, {esc(skill)}, {time_sec}) "
            f"ON CONFLICT (id) DO NOTHING;"
        )

for sheet in ['QR Master', 'Silver', 'Gold']:
    process_qr_sheet(wb[sheet], sheet)
    print(f"  {sheet}: done")

lines.append(f"\n-- QR totals: {len(seen_datasets)} datasets, {sum(1 for l in lines if 'qr_questions' in l and 'INSERT' in l)} questions\n")

# ═══════════════════════════════════════════════════════════════════
# SJT
# ═══════════════════════════════════════════════════════════════════
print("Reading SJT data …")
wb2 = openpyxl.load_workbook(SJT_FILE, read_only=True)

lines.append("-- ─── SJT questions ──────────────────────────────────────────────────────────")

AR_OPTIONS = [
    "A very appropriate thing to do",
    "Appropriate, but not ideal",
    "Inappropriate, but not awful",
    "A very inappropriate thing to do",
]
IR_OPTIONS = [
    "Very important",
    "Important",
    "Of minor importance",
    "Not important at all",
]

def normalise_ar(raw):
    raw = str(raw).strip().rstrip('.')
    for opt in AR_OPTIONS:
        if opt.lower() in raw.lower():
            return opt
    return raw

def normalise_ir(raw):
    raw = str(raw).strip().rstrip('.')
    for opt in IR_OPTIONS:
        if opt.lower() in raw.lower():
            return opt
    return raw

def parse_ml_options(raw):
    """Return (a_text, b_text, c_text) from newline-separated 'A. ...\nB. ...\nC. ...'"""
    parts = {'A': '', 'B': '', 'C': ''}
    for line in str(raw).split('\n'):
        m = re.match(r'^([A-C])\.\s*(.*)', line.strip())
        if m:
            parts[m.group(1)] = m.group(2).strip()
    return parts['A'], parts['B'], parts['C']

def parse_ml_correct(raw):
    """'Most appropriate: A. Least appropriate: C.' → mostCor=0, leastCor=2"""
    raw = str(raw)
    most = re.search(r'Most[^:]*:\s*([A-C])', raw, re.I)
    least = re.search(r'Least[^:]*:\s*([A-C])', raw, re.I)
    mc = ord(most.group(1).upper()) - ord('A') if most else 0
    lc = ord(least.group(1).upper()) - ord('A') if least else 2
    return mc, lc

seen_sjt = set()
sjt_count = 0

def process_sjt_sheet(ws, fmt):
    global sjt_count
    rows = list(ws.iter_rows(values_only=True))
    data = [r for r in rows if r[0] and isinstance(r[0], str) and re.match(r'^SJT\d+', r[0])]
    for r in data:
        q_id      = r[0]
        if q_id in seen_sjt:
            continue
        seen_sjt.add(q_id)

        scen_num   = r[1]
        scen_title = r[2] or ''
        scenario   = r[3] or ''
        theme      = r[4] or ''
        focus      = r[5] or ''
        difficulty = r[6] or 'Gold'
        question   = r[8] or ''
        raw_opts   = r[9] or ''
        raw_ans    = r[10] or ''
        walkthru   = r[11] or ''

        if fmt == 'appropriateness':
            correct = normalise_ar(raw_ans)
            a, b, c = '', '', ''
        elif fmt == 'importance':
            correct = normalise_ir(raw_ans)
            a, b, c = '', '', ''
        else:  # most-least
            a, b, c = parse_ml_options(raw_opts)
            mc, lc = parse_ml_correct(raw_ans)
            # encode as "mostCor:X|leastCor:Y" for easy parsing
            correct = f"most:{mc}|least:{lc}"

        scen_num_sql = str(scen_num) if scen_num else 'NULL'

        lines.append(
            f"INSERT INTO sjt_questions "
            f"(id, format, scenario_num, scenario_title, scenario, professional_theme, theme_focus, "
            f"difficulty, question, option_a, option_b, option_c, correct_answer, walkthrough) VALUES "
            f"({esc(q_id)}, {esc(fmt)}, {scen_num_sql}, {esc(scen_title)}, {esc(scenario)}, "
            f"{esc(theme)}, {esc(focus)}, {esc(difficulty)}, {esc(question)}, "
            f"{esc(a)}, {esc(b)}, {esc(c)}, {esc(correct)}, {esc(walkthru)}) "
            f"ON CONFLICT (id) DO NOTHING;"
        )
        sjt_count += 1

process_sjt_sheet(wb2['Appropriateness'], 'appropriateness')
print(f"  Appropriateness: done")
process_sjt_sheet(wb2['Importance'], 'importance')
print(f"  Importance: done")
process_sjt_sheet(wb2['Most & Least'], 'most-least')
print(f"  Most & Least: done")

lines.append(f"\n-- SJT total: {sjt_count} questions")

# Write output
with open(OUT_FILE, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"\nDone → {OUT_FILE}")
print(f"  QR:  {len(seen_datasets)} datasets")
qr_q_count = sum(1 for l in lines if l.startswith('INSERT INTO qr_questions'))
print(f"  QR:  {qr_q_count} questions")
print(f"  SJT: {sjt_count} questions")
