// SJT answer patch for Mock 1
// correct index: approp questions: 0=Very appropriate, 1=Appropriate but not ideal, 2=Inappropriate but not awful, 3=Very inappropriate
// correct index: import questions: 0=Very important, 1=Important, 2=Of minor importance, 3=Not important at all
// mostleast questions: correctMost + correctLeast (0-3 index into factors array)

export const SJT_ANSWERS: Record<string, { correct: number; correctMost?: number; correctLeast?: number; explanation: string }> = {
  "MOCK1-SJT-001": { correct: 0, explanation: "A possible allergy affecting prescribing is an immediate safety issue; a polite reminder is proportionate and within a student's role." },
  "MOCK1-SJT-002": { correct: 3, explanation: "Hierarchy does not justify silence where relevant safety information may have been missed." },
  "MOCK1-SJT-003": { correct: 0, explanation: "Potential impact on safe prescribing is the central consideration." },
  "MOCK1-SJT-004": { correct: 0, explanation: "Early, honest communication lets the ward adjust expectations and is the most responsible response to an unavoidable delay." },
  "MOCK1-SJT-005": { correct: 2, explanation: "Remaining silent about lateness is avoidant and unprofessional, although the isolated 20-minute delay is not itself a major safety breach." },
  "MOCK1-SJT-006": { correct: 1, explanation: "Staff expectations and teaching arrangements are relevant, but the situation is primarily a reliability issue rather than an immediate safety risk." },
  "MOCK1-SJT-007": { correct: 0, explanation: "Checking with the supervisor protects consent, privacy and local procedure before the student becomes involved." },
  "MOCK1-SJT-008": { correct: 3, explanation: "Using a personal phone creates avoidable privacy and information-governance risks and is outside an appropriate student boundary." },
  "MOCK1-SJT-009": { correct: 0, explanation: "Storage and access are fundamental when any patient image is created or handled." },
  "MOCK1-SJT-010": { correct: 0, explanation: "Addressing the issue privately and offering a lawful alternative is proportionate and constructive." },
  "MOCK1-SJT-011": { correct: 2, explanation: "Limited sharing does not remove copyright or integrity concerns, so knowingly leaving copied material is still inappropriate." },
  "MOCK1-SJT-012": { correct: 0, explanation: "Permission to reproduce the material directly determines whether the group is using it appropriately." },
  "MOCK1-SJT-013": { correct: 0, explanation: "Private support combined with proportionate escalation if patient-related work is affected balances colleague welfare with safety." },
  "MOCK1-SJT-014": { correct: 3, explanation: "Sharing Sam's private home circumstances with the whole group is unnecessary and breaches his privacy." },
  "MOCK1-SJT-015": { correct: 0, explanation: "Once tiredness affects patient-related activity, safety becomes a high-priority consideration." },
  "MOCK1-SJT-016": { correct: 0, explanation: "Stopping identifiable case discussion in a public place promptly protects confidentiality." },
  "MOCK1-SJT-017": { correct: 3, explanation: "A patient can be identifiable from combined details even without a surname; ignoring the risk is unacceptable." },
  "MOCK1-SJT-018": { correct: 0, explanation: "Whether the details can identify the patient is central to confidentiality risk." },
  "MOCK1-SJT-019": { correct: 0, explanation: "Consent is ongoing and can be withdrawn; accepting the decision without pressure is appropriate." },
  "MOCK1-SJT-020": { correct: 3, explanation: "Using the student's training need to persuade a patient risks coercion and undermines voluntary consent." },
  "MOCK1-SJT-021": { correct: 0, explanation: "The ability to withdraw consent at any time is fundamental." },
  "MOCK1-SJT-022": { correct: 0, explanation: "Correcting the error and being open with the supervisor preserves accuracy and accountability." },
  "MOCK1-SJT-023": { correct: 2, explanation: "Correcting the value limits harm, but deliberately concealing the error undermines openness and learning." },
  "MOCK1-SJT-024": { correct: 1, explanation: "Checking nearby entries is a sensible quality-control step, though less urgent than correcting and reporting the known error." },
  "MOCK1-SJT-025": { correct: 0, explanation: "A calm challenge addresses disrespect without unnecessary confrontation and supports professional culture." },
  "MOCK1-SJT-026": { correct: 2, explanation: "Laughing along reinforces disrespectful behaviour even if intended only to avoid awkwardness." },
  "MOCK1-SJT-027": { correct: 1, explanation: "The effect on group culture is relevant because unchallenged attitudes can become normalised, though no patient is immediately at risk." },
  "MOCK1-SJT-028": { correct: 0, explanation: "Theo should recognise his competence limit and seek supervision or an appropriately trained person." },
  "MOCK1-SJT-029": { correct: 3, explanation: "Watching a procedure is not equivalent to competence; workload pressure does not justify unsafe independent practice." },
  "MOCK1-SJT-030": { correct: 0, explanation: "Training and assessed competence are decisive before undertaking a clinical task." },
  "MOCK1-SJT-031": { correct: 0, explanation: "Deleting the post is an appropriate corrective action once Mia recognises the professionalism concern." },
  "MOCK1-SJT-032": { correct: 2, explanation: "Absence of a name does not make patient-related social-media commentary automatically acceptable; leaving it up remains inappropriate." },
  "MOCK1-SJT-033": { correct: 0, explanation: "Private posts can be copied or redistributed, so potential reach is highly relevant." },
  "MOCK1-SJT-034": { correct: 0, explanation: "Records must only be accessed for legitimate purposes; directing the friend to normal channels is appropriate." },
  "MOCK1-SJT-035": { correct: 3, explanation: "Looking up even limited information for a personal reason is unauthorised access." },
  "MOCK1-SJT-036": { correct: 0, explanation: "A legitimate care-related reason is fundamental to authorised record access." },
  "MOCK1-SJT-037": { correct: 0, explanation: "Ensuring the patient receives clarification before leaving protects understanding and safe medicine use." },
  "MOCK1-SJT-038": { correct: 3, explanation: "A student should not independently provide detailed medication instructions beyond their competence or supervision." },
  "MOCK1-SJT-039": { correct: 0, explanation: "Understanding the plan sufficiently to use medication safely is a central patient-safety issue." },
  "MOCK1-SJT-040": { correct: 0, explanation: "Locking or logging out prevents unauthorised access and is standard information-security practice." },
  "MOCK1-SJT-041": { correct: 3, explanation: "Another staff member's presence does not establish that they are authorised to view the open record." },
  "MOCK1-SJT-042": { correct: 0, explanation: "Authorisation to view the displayed information is the key confidentiality consideration." },
  "MOCK1-SJT-043": { correct: 0, explanation: "Checking local policy or asking a supervisor is proportionate when the gift is small but the rules are uncertain." },
  "MOCK1-SJT-044": { correct: 2, explanation: "A fixed £10 assumption is unsupported; acceptability depends on policy, context and professional boundaries, not only price." },
  "MOCK1-SJT-045": { correct: 1, explanation: "Potential obligation or boundary effects are relevant to deciding whether a gift is appropriate." },
  "MOCK1-SJT-046": { correct: 0, explanation: "A young person's request for private discussion should be acknowledged rather than automatically overridden by a parent." },
  "MOCK1-SJT-047": { correct: 3, explanation: "Parental presence does not automatically remove the young person's autonomy or privacy interests." },
  "MOCK1-SJT-048": { correct: 0, explanation: "Private information may not be disclosed in front of a parent, so this is a central communication consideration." },
  "MOCK1-SJT-049": { correct: 0, explanation: "A brief identity check is proportionate where wrong-patient results may be influencing a treatment decision." },
  "MOCK1-SJT-050": { correct: 3, explanation: "Uncertainty is a reason to verify, not a reason to remain silent when the potential consequence is serious." },
  "MOCK1-SJT-051": { correct: 0, explanation: "Using another patient's results could cause major harm, making the potential consequence highly important." },
  "MOCK1-SJT-052": { correct: 0, explanation: "Asking before leaving respects the scheduled commitment while allowing the supervisor to release Kai if appropriate." },
  "MOCK1-SJT-053": { correct: 2, explanation: "Leaving early without telling anyone is unreliable and discourteous even if no patients are currently waiting." },
  "MOCK1-SJT-054": { correct: 1, explanation: "Whether the supervisor expects attendance until the scheduled end is directly relevant to professional responsibility." },
  "MOCK1-SJT-055": { correct: 0, explanation: "A polite reminder immediately addresses an avoidable infection-control risk." },
  "MOCK1-SJT-056": { correct: 3, explanation: "Fear of appearing disrespectful should not override patient safety where a simple reminder can prevent risk." },
  "MOCK1-SJT-057": { correct: 0, explanation: "Potential infection risk to the patient is the central concern." },
  "MOCK1-SJT-058": { correct: 0, explanation: "Private contact gives Priyanka a fair opportunity to explain and allows the group to address the problem proportionately." },
  "MOCK1-SJT-059": { correct: 3, explanation: "Removing her name immediately without discussion is disproportionate and could unfairly penalise someone without understanding the circumstances." },
  "MOCK1-SJT-060": { correct: 0, explanation: "Possible circumstances affecting participation should be understood before deciding on a fair response." },
  "MOCK1-SJT-061": { correct: 0, explanation: "Ben appropriately recognises his limits and redirects the medication concern to a qualified clinician." },
  "MOCK1-SJT-062": { correct: 3, explanation: "Advising a patient to stop prescribed medication without adequate information or authority creates a direct safety risk." },
  "MOCK1-SJT-063": { correct: 0, explanation: "Lack of sufficient information and authority is fundamental to recognising the limits of Ben's role." },
  "MOCK1-SJT-064": { correct: 0, explanation: "Discussing how the near miss occurred supports learning and future prevention without treating the student punitively." },
  "MOCK1-SJT-065": { correct: 2, explanation: "Suppressing a near miss wastes an opportunity to learn, although no harm occurred in this instance." },
  "MOCK1-SJT-066": { correct: 0, explanation: "Understanding causes can prevent a future error, making reflection highly important." },
  "MOCK1-SJT-067": { correct: 0, explanation: "Acknowledging frustration and seeking accurate information is empathetic while staying within the student's role." },
  "MOCK1-SJT-068": { correct: 3, explanation: "Making a definite promise without reliable information is dishonest and can further damage trust." },
  "MOCK1-SJT-069": { correct: 0, explanation: "Accuracy should take priority over reassurance that may later prove false." },
};

// DM explanation patch (YN-5 questions had empty explanations)
export const DM_EXPLANATIONS: Record<string, string> = {
  "MOCK1-DM-001": "1 Yes: astronomy ⊂ science, science ∩ drama = ∅ → astronomy ∩ drama = ∅. 2 Yes: some drama are musicians; drama ∩ science = ∅ → those musicians not science. 3 Yes: drama members cannot be astronomy members. 4 No: only some musicians are drama members; others could be astronomy. 5 No: 'all astronomy are science' doesn't require any astronomy to exist.",
  "MOCK1-DM-005": "1 No: frost alert alone doesn't trigger manual check (need both frost AND high-wind). 2 Yes: indoor sensors can't send high-wind alerts, so can't send both. 3 Yes: stated directly. 4 Yes: frost alert without high-wind alert → no manual check. 5 No: only some outdoor sensors are checked.",
  "MOCK1-DM-009": "1 Yes: C 75% is highest. 2 Yes: 80/160 = 50%. 3 No: 263/380 ≈ 69.2%, not >70%. 4 Yes: A 40% > C 35%. 5 Yes: 104 in B > 84 in A.",
  "MOCK1-DM-013": "1 Yes: protected → not polluted → doesn't require testing for pollution. 2 Yes: some protected are river sites; protected not polluted → some river not polluted. 3 No: no premise links river sites to further testing. 4 Yes: equivalent contrapositive. 5 No: only some protected are river; not all river are protected.",
  "MOCK1-DM-016": "1 Yes: B in Gallery; A can't be Café/Shop/Gallery → A must be Tickets. 2 Yes: B in Gallery, A in Tickets → C in Café or Shop. 3 Yes: B is the only Gallery volunteer. 4 Yes: if C is Café, only D is left for Shop. 5 No: A, not D, is in Tickets.",
  "MOCK1-DM-020": "1 Yes: X waterfowl = 96/240 = 40%. 2 Yes: Y 45% > X 40% > Z 35%. 3 Yes: Z waders 40% > X waders 30%. 4 Yes: Z 105 > X 96. 5 No: total waders 237/720 ≈ 33%, not 25%.",
  "MOCK1-DM-026": "1 Yes: some safety-trained are researchers; no researcher is finance → some safety-trained not finance. 2 No: technicians are safety-trained but not necessarily researchers. 3 Yes: stated directly. 4 No: no premise links technicians to researchers. 5 Yes: contrapositive of 'no researcher is finance officer'.",
  "MOCK1-DM-029": "Only valid rota: K Mon, M Tue, L Wed, P Thu, N Fri. 1 Yes: K works Monday. 2 Yes: P works Thursday. 3 No: M works Tuesday not Thursday. 4 No: N works Friday not Tuesday. 5 No: K must be before M, cannot be Friday.",
  "MOCK1-DM-032": "1 Yes: some wildlife-zone visitors use boating lake → some boating-lake users visit wildlife zone. 2 No: only those who use the boating lake must wear life jackets. 3 Yes: no rule bans bicycles from wildlife zone. 4 Yes: stated directly. 5 Yes: some wildlife visitors use boating lake, and all boating-lake users must wear life jackets.",
};
