type Block = [string, string];
type FoundationPage = { id: string; title: string; subtitle: string; intro: string; blocks: Block[]; tip: [string, string] };
type TopicPage = { id: string; title: string; description: string; spot: string; rules: string[]; steps: string[]; traps: string[]; example?: [string, string] };
type GuideGroup = { id: string; label: string; icon: string; topics: TopicPage[] };
export type GuideSection = { short: string; label: string; color: string; deep: string; tint: string; tagline: string; stats: [string, string][]; foundations: FoundationPage[]; groups: GuideGroup[]; official?: string };

const F = (id: string, title: string, subtitle: string, intro: string, blocks: Block[], tip: [string, string]): FoundationPage => ({ id, title, subtitle, intro, blocks, tip });
const T = (id: string, title: string, description: string, spot: string, rules: string[], steps: string[], traps: string[], example?: [string, string]): TopicPage => ({ id, title, description, spot, rules, steps, traps, example });

export const studyGuideSections: Record<string, GuideSection> = {
  vr: {
    short: "VR", label: "Verbal Reasoning", color: "#2D7FF9", deep: "#1A5FD0", tint: "#EAF2FF",
    tagline: "Read quickly, but stay strict about what the passage actually proves.",
    stats: [["44", "questions"], ["22 min", "section time"], ["2", "question formats"], ["11", "topic guides"]],
    foundations: [
      F("what-vr-tests", "What VR is really testing", "The reading skills underneath every VR question.", "VR is less about remembering every line and more about controlling evidence. You need to find the right part of the passage, understand exactly what it says and avoid adding a story of your own.", [["Finding evidence", "Use names, dates, technical terms and contrast words as anchors. Then read the whole sentence around the match."], ["Direct facts and inference", "A direct answer is stated. An inference joins details, but it still has to be unavoidable."], ["Scope and certainty", "Some is not all; may is not will. Small wording changes can make an answer too broad or too certain."], ["Whose view is it?", "Keep the author's view separate from a person they quote, describe or challenge."]], ["A useful check", "Could you point to the exact words that make your answer safe?"]),
      F("format-timing", "Format and timing", "How to handle the section without rushing blindly.", "You have 22 minutes for 44 questions, usually arranged as 11 passages with four questions each. Think in passage blocks rather than restarting your reading process for every question.", [["True / False / Can't Tell", "Decide whether the statement is supported, contradicted or left unresolved."], ["Multiple choice", "Choose the single best option. Distractors often borrow a real detail and quietly alter it."], ["A practical pace", "Roughly two minutes per passage is a helpful starting point, not a rule you must obey perfectly."], ["Flag with a plan", "Choose your best answer first, flag it and move. Never leave a question blank just because it is awkward."]], ["Protect easy marks", "One stubborn item is not worth losing several questions at the end."]),
      F("passage-evidence", "Use only the passage", "The rule that stops outside knowledge sneaking in.", "Treat each passage as a closed world. Something may be sensible or true in real life, but that does not make it an answer unless this passage supports it.", [["Supported", "The passage states the point or gives enough information for it to follow necessarily."], ["Contradicted", "The passage gives evidence for the opposite. This is what you need before choosing False."], ["Not settled", "If the passage neither proves nor contradicts a claim, the answer is Can't Tell."], ["Keep the boundaries", "Evidence about one sample, year or place cannot automatically be stretched to everyone or forever."]], ["The courtroom check", "If someone asked you to show the evidence, could you do it without saying 'it just makes sense'?"]),
      F("timing-triage", "Timing and triage", "Spend your time where it is most likely to earn a mark.", "A long passage is not automatically hard. Clear headings and distinctive names can make it easy to scan, while a short abstract paragraph can take longer.", [["Question first", "The stem tells you what to search for and how much of the passage you probably need."], ["Search by meaning", "Questions paraphrase, so scan for the idea as well as the exact word."], ["Know when to move", "If rereading is not reducing the uncertainty, choose, flag and protect the rest of the section."], ["Return intelligently", "Go back first to questions where you know the exact distinction you need to check."]], ["Build speed gradually", "Start accurate, move to short timed sets, then practise full sections."]),
      F("common-traps", "Common VR traps", "The small changes that make tempting answers wrong.", "Wrong options are rarely random. They usually keep enough of the passage to feel familiar, then change one relationship, group, time frame or level of certainty.", [["Keyword match", "The same words appear, but the sentence means something different."], ["Extreme wording", "All, never, only and proves need very strong evidence."], ["Half-right answer", "The first clause is supported and the second adds something new."], ["Reversal", "Cause and effect, earlier and later, or speaker and author are swapped."], ["Scope drift", "A finding about some people or one period becomes a claim about everyone."], ["False versus Can't Tell", "No evidence for a claim is not the same as evidence against it."]], ["Name the trap", "Instead of saying 'that option feels wrong', say exactly what it changed."]),
    ],
    groups: [
      { id: "tfct", label: "True / False / Can't Tell", icon: "T/F", topics: [
        T("tfct-direct", "Direct Retrieval", "Match a statement to a fact the passage gives you directly.", "Look for a distinctive name, date, place, event or number that can take you to one small area.", ["A paraphrase can still be true.", "Every part of a joined statement must be supported.", "False needs a contradiction; silence means Can't Tell."], ["Break the statement into its parts.", "Scan for the strongest anchor.", "Read the whole evidence sentence.", "Compare person, time, quantity and certainty.", "Decide supported, contradicted or unresolved."], ["Stopping at the first keyword", "Missing a negative", "Calling missing information False"], ["Quick example", "If a branch opened in 2018 but Sunday trading began two years later, the claim that it traded Sundays when it opened is False."]),
        T("tfct-inference", "Inference", "Join details only when the conclusion has to follow.", "The answer is not repeated word for word, so you need a short chain between two or more facts.", ["Necessary is stronger than likely.", "Do not add a cause the passage never gives.", "Keep people, groups and time periods separate."], ["Write the shortest evidence chain.", "Ask whether another allowed situation exists.", "If a gap remains, choose Can't Tell.", "Use False only when the passage rules the claim out."], ["Confusing possible with certain", "Reversing a rule", "Joining facts from different groups"], ["Quick example", "If every manuscript catalogued before 1900 is stored off-site and one was catalogued in 1887, it must be stored off-site."]),
        T("tfct-comparisons", "Comparisons & Relationships", "Keep amounts, rankings and relationships pointing the right way.", "Watch for more, less, earlier, later, higher, lower, twice and percentage language.", ["Keep the comparison base the same.", "Check that the time period matches.", "A relationship is not automatically a cause."], ["Name the two things being compared.", "Write a tiny arrow or value.", "Use an easy base such as 100 if needed.", "Check direction, units and timing."], ["Reversing A and B", "Changing the percentage base", "Comparing different periods"], ["Quick example", "If Oak is 20% above 100 and Elm is 10% below Oak, Elm is 108—not below 100."]),
        T("tfct-scope", "Scope & Evidence", "Judge whether the passage says enough for the whole statement.", "The topic looks familiar, but the claim may be broader, stronger or more causal than the evidence.", ["Track population, place, time and certainty.", "Some does not prove all.", "Association does not prove causation."], ["Underline the scope words.", "Locate the evidence boundary.", "Ask whether the claim stays inside it.", "Choose Can't Tell when an unresolved gap remains."], ["Sample-to-population jumps", "Short-term to permanent claims", "Assuming a cause"], ["Quick example", "A result in three schools during one term does not prove a national or permanent effect."]),
      ]},
      { id: "mcq", label: "Multiple Choice", icon: "A–D", topics: [
        T("mcq-direct", "Direct Retrieval (MCQ)", "Find the option that accurately restates a specific detail.", "The stem asks who, what, when, where, how many or according to the passage.", ["Search with the most distinctive clue.", "Read enough context to catch negatives and qualifications.", "Test every clause of the option."], ["Mark the target detail.", "Scan for an anchor.", "Read around the match.", "Compare each option with the evidence."], ["Near-match wording", "Wrong time period", "Right fact attached to the wrong person"], ["Quick example", "If a scheme was planned in 2019 and launched in 2021, 'planned in 2019' is safe; 'operating in 2019' is not."]),
        T("mcq-inference", "Inference (MCQ)", "Choose the conclusion that is best supported rather than merely plausible.", "The stem asks what can be inferred, concluded or most reasonably suggested.", ["The right answer uses the fewest assumptions.", "A strong inference can still be cautious.", "Do not turn a trend into a cause."], ["Identify the evidence region.", "Form the narrowest conclusion.", "Test each option for added assumptions.", "Choose the one that stays closest to the text."], ["Outside knowledge", "Extreme wording", "Cause from correlation"], ["Quick example", "If volunteers stayed longer when roles were clearer, the safe inference is that clarity may be linked to retention—not that it was the only cause."]),
        T("mcq-main-idea", "Main Idea & Purpose", "Find what the passage is mainly trying to do.", "The question asks for the main point, best summary, purpose or best title.", ["Prioritise the opening, conclusion and major contrast turns.", "Examples support the main idea; they are not automatically the main idea.", "A title needs the right topic and angle."], ["Read the opening and final paragraph.", "Summarise the passage in one sentence.", "Check the middle for a major shift.", "Reject options that are too narrow or too broad."], ["Choosing a vivid detail", "Picking the topic without the author's angle", "Ignoring the conclusion"], ["Quick example", "A passage that introduces a policy, examines unexpected effects and calls for review is mainly evaluating the policy—not just describing one example."]),
        T("mcq-viewpoint", "Author & Speaker Viewpoint", "Keep opinions attached to the right person and strength.", "Look for author, critic, researcher, supporter, according to and attitude wording.", ["Quoted material is not automatically the author's view.", "Track reporting verbs such as claims, warns or concedes.", "Match cautious and strong language carefully."], ["Name the speaker.", "Find the view statement.", "Read the author's framing around it.", "Compare the strength of each option."], ["Speaker-author swaps", "Treating neutrality as support", "Turning cautious concern into certainty"], ["Quick example", "If the author calls a critic's warning 'premature', the warning belongs to the critic, not the author."]),
        T("mcq-meaning", "Meaning in Context", "Choose the meaning a word or phrase has in this sentence.", "The question quotes a word and asks what it most nearly means here.", ["Context beats the most familiar dictionary meaning.", "Tone and argument direction matter.", "The replacement should keep the sentence logical."], ["Read the sentence before and after.", "Predict a simple meaning.", "Swap each option into the sentence.", "Choose the best logical and tonal fit."], ["Picking the familiar definition", "Ignoring figurative use", "Choosing a synonym with the wrong tone"], ["Quick example", "If an inquiry 'casts light on' a process, the phrase means explains or reveals—not physically illuminates."]),
      ]},
    ],
  },
  dm: {
    short: "DM", label: "Decision Making", color: "#8B6BFF", deep: "#6747D8", tint: "#F1ECFF",
    tagline: "Turn rules and information into the one conclusion you can defend.",
    stats: [["35", "questions"], ["37 min", "section time"], ["2", "answer formats"], ["6", "topic guides"]],
    foundations: [
      F("what-dm-tests", "What DM is really testing", "Formal reasoning, not what feels likely.", "DM asks whether a conclusion follows from the information you have been given. The everyday story may sound realistic, but only the stated rules and evidence count.", [["Deduction", "Use category and conditional rules without adding real-world assumptions."], ["Data interpretation", "Track totals, denominators, time periods, units and uncertainty."], ["Constraint solving", "Arrange order, groups or assignments while satisfying every rule."], ["Argument quality", "Choose reasons that are relevant to the decision and matter to its outcome."], ["Sets and probability", "Use diagrams and calculations to make hidden relationships visible."]], ["A good habit", "Translate the information before you judge the answer."]),
      F("dm-format", "Format and scoring", "Know what changes between the two question styles.", "You will see single-answer multiple choice questions and five-statement Yes/No sets. In a five-statement set, judge each line independently rather than letting one answer influence the next.", [["Single-answer MCQ", "Four options, with one best answer."], ["Five-statement sets", "A fully correct set earns two marks; getting four of five correct can earn partial credit."], ["Workload varies", "A short syllogism can be quicker than a multi-rule puzzle, so budget by burden."], ["Keep working visible", "A clean grid or diagram saves time when you return to a flagged question."]], ["Secure the easy decisions", "Direct consequences should be answered before you wrestle with an awkward branch."]),
      F("logical-language", "Logical language", "Small words can completely change the rule.", "Words such as all, some, no, only, unless and most have precise logical meanings. Translate them into arrows or set relationships before testing a conclusion.", [["All / some / no", "'Some' means at least one; it does not mean exactly one or 'not all'."], ["If A, then B", "A leads to B. The contrapositive not-B leads to not-A is valid; the converse is not."], ["Only if", "A only if B means A → B. 'Only A are B' points the other way: B → A."], ["Unless", "A unless B can be read as: if not B, then A."], ["Must / could", "Disprove a must statement with one counterexample; prove could with one valid arrangement."]], ["Pause on tiny words", "Circle only, unless, not, every, some and most before doing anything else."]),
      F("dm-diagrams", "Diagramming and workspace", "Use the smallest picture that captures the rules.", "The aim is not to produce beautiful diagrams. It is to move information out of your head so you can test options without rereading the whole question.", [["Nested circles", "Useful for all, some and no category relationships."], ["Grids", "Best for assigning people, days, rooms or features."], ["Slots and blocks", "Useful for order questions and immediate-before rules."], ["Trees and tables", "Good for sequential or conditional probability."], ["Readable notation", "Write short rules such as L < N or R → not S."]], ["Do not overbuild", "Start with fixed facts and add only what the question needs."]),
      F("dm-traps", "Common DM traps", "The reasoning shortcuts that quietly break a conclusion.", "Most DM errors come from changing a rule, assuming something exists or answering what is likely instead of what must follow.", [["Converse error", "A → B does not mean B → A."], ["Existence assumption", "'All A are B' does not prove that any A exist."], ["Possibility as certainty", "One valid arrangement proves could, not must."], ["Hidden denominator", "A percentage can change meaning when the comparison group changes."], ["Irrelevant argument", "A true or emotional statement can still fail to address the proposal."], ["Replacement error", "Without-replacement probability needs a changed second denominator."]], ["Ask the right question", "Is this guaranteed, merely possible or actually ruled out?"]),
    ],
    groups: [
      { id: "dm-topics", label: "Question skills", icon: "DM", topics: [
        T("syllogisms", "Syllogisms", "Decide what must follow from category or conditional premises.", "Short statements use all, some, no, if, only or unless, followed by conclusions to test.", ["Use only the given structure.", "The contrapositive is valid; the converse is not.", "Universal statements do not guarantee existence."], ["Translate each premise.", "Draw the smallest set picture or arrow chain.", "Test one conclusion at a time.", "Search for a counterexample when the claim says must."], ["Assuming existence", "Treating some as exactly one", "Combining different people"], ["See it in action", "All R are S and no S are T means no R are T. Reversing 'no R are T' to 'no T are R' is also safe because exclusion works both ways."]),
        T("interpreting-information", "Interpreting Information", "Judge conclusions from tables, charts and short reports.", "You are given data and usually five statements that must each be checked independently.", ["Use the exact denominator and time period.", "Keep number, rate and percentage separate.", "Association does not prove cause."], ["Read the title, units and footnotes.", "Locate the exact values.", "Recalculate ratios or percentages.", "Compare the statement with the available precision."], ["Wrong axis or period", "Unequal group sizes", "Cumulative versus yearly values"], ["See it in action", "40 successes out of 50 is 80%; 72 out of 100 is 72%. The first group has the higher rate even though the second has more successes."]),
        T("venn-diagrams", "Venn Diagrams", "Reason about inclusion, overlap, exclusion and counts.", "The question describes groups or shows circles and asks what must fit where.", ["All places one set inside another.", "No removes overlap.", "Some guarantees at least one occupied region.", "Circle size is not numerical unless stated."], ["Draw universal relationships first.", "Add exclusions.", "Place existential facts last.", "Fill specific overlaps before totals."], ["Double subtraction", "Forgetting the outside region", "Treating drawn scale as data"], ["See it in action", "With 80 people, X=45, Y=38 and both=17: X-only is 28, Y-only is 21, the union is 66 and 14 are in neither."]),
        T("arguments-assumptions", "Arguments & Assumptions", "Judge whether a reason genuinely supports a proposal.", "The question asks for the strongest argument or an assumption needed for a conclusion.", ["A strong argument is relevant and important.", "Detail and emotional force do not guarantee strength.", "Use the negation test for assumptions."], ["State the exact decision.", "Remove irrelevant options.", "Check whether the reason affects an important outcome.", "For assumptions, negate each candidate and see whether the argument collapses."], ["True but irrelevant claims", "Circular reasoning", "Extreme unsupported consequences"], ["See it in action", "For extending library hours, evidence that the people who need the service cannot attend within current hours is more relevant than saying libraries are generally valuable."]),
        T("logic-puzzles", "Logic Puzzles", "Build an arrangement that satisfies every condition.", "Look for ordering, assignment, grouping or selection rules and stems such as must, could or cannot.", ["Place fixed rules first.", "Keep conditional branches separate.", "Capacity limits are rules too."], ["Choose slots, a grid or groups.", "Add fixed facts.", "Chain linked rules.", "Branch the most restrictive condition.", "Test options against every rule."], ["Ignoring capacity", "Confusing before with immediately before", "Mixing separate branches"], ["See it in action", "If K is before M and P is immediately after K, treat KP as a block before placing M."]),
        T("probability", "Probability", "Calculate single, combined and conditional outcomes.", "Look for and, or, without replacement, given that and at least one.", ["AND usually means multiply along a path.", "OR adds mutually exclusive routes.", "Without replacement changes the next fraction.", "At least one is often easiest with 1 minus none."], ["List the relevant outcomes.", "Mark replacement and dependence.", "Build each path.", "Add valid paths.", "Check the answer stays between 0 and 1."], ["Adding overlapping outcomes", "Assuming independence", "Reversing conditional probability"], ["See it in action", "From a bag with 3 red and 2 blue, two reds without replacement is 3/5 × 2/4 = 3/10."]),
      ]},
    ],
  },
  qr: {
    short: "QR", label: "Quantitative Reasoning", color: "#3DBE6C", deep: "#259650", tint: "#EDFBF3",
    tagline: "Choose the right numbers, run a clean calculation and keep the units under control.",
    stats: [["36", "questions"], ["26 min", "section time"], ["1", "answer format"], ["6", "topic guides"]],
    foundations: [
      F("what-qr-tests", "What QR is really testing", "Accessible maths used quickly and accurately.", "The calculations are usually familiar. The challenge is deciding what the question wants, choosing the right figures and keeping units and precision under control.", [["Select the data", "Find the correct row, column, series, period and subgroup."], ["Translate the wording", "Turn 'of', 'per', 'increase', 'remaining' and 'at this rate' into an operation."], ["Handle several steps", "Keep intermediate values meaningful rather than typing a long mystery calculation."], ["Check the answer", "Estimate first so a misplaced decimal or wrong denominator is obvious."], ["Finish properly", "Use the requested unit and only round at the end unless told otherwise."]], ["Before the calculator", "Say what the answer represents and roughly how large it should be."]),
      F("qr-format-calculator", "Format, timing and calculator", "Use the calculator as a tool, not a thinking substitute.", "You have 26 minutes for 36 single-answer questions. Some items are quick lookups; others need several steps, so a perfectly even time split is not realistic.", [["Set up first", "Decide the operation before entering figures."], ["One clean expression", "Use brackets and a clear route instead of repeatedly clearing and retyping."], ["Options can help", "Estimate, compare scale or work backwards when that is faster."], ["Flag intelligently", "Leave a best answer and a readable setup before moving on."], ["Reuse the display", "Several questions may use the same table or chart, so keep your orientation."]], ["Calculator check", "Read the displayed number back in context—money, people, minutes or percentage?"]),
      F("core-number-skills", "Core number skills", "The small toolkit that appears everywhere in QR.", "You do not need advanced maths. You do need dependable percentage, ratio, rate and average skills that you can recognise without hesitation.", [["Percentages", "Percentage change uses the original value as the denominator."], ["Ratios", "Add the parts, find one part and preserve the stated order."], ["Rates", "Write units beside the calculation so you know whether to multiply or divide."], ["Averages", "Mean equals total divided by count; combined means usually require rebuilt totals."], ["Precision", "Keep full calculator values during working and round once at the end."]], ["Dimensional check", "If the units do not combine into the requested unit, the setup is probably wrong."]),
      F("reading-data", "Reading tables, charts and graphs", "Orient yourself before grabbing a number.", "A correct calculation using the wrong series is still wrong. Titles, labels, legends, axes, baselines and footnotes are part of the question.", [["Tables", "Trace the requested row and column, then check units and notes."], ["Bar charts", "Watch grouped, stacked and 100% bars, plus any truncated baseline."], ["Line graphs", "Match the correct series and remember a cumulative value is not a period value."], ["Pie charts", "Use part/whole or angle/360."], ["Scatter plots", "Describe association and outliers, not causation."]], ["Slow down for five seconds", "Those first five seconds can prevent a full minute of calculating the wrong thing."]),
      F("qr-traps", "Common QR traps", "Most lost marks come from setup, not arithmetic.", "A calculator will faithfully produce the wrong answer if you feed it the wrong denominator, unit or data series.", [["Wrong base", "Percentage change divides by the original value."], ["Percentage points", "A move from 40% to 50% is 10 points but a 25% relative increase."], ["Early rounding", "Small errors grow across multi-step questions."], ["Unequal averages", "Do not average group means without weighting by group size."], ["Unit mismatch", "Minutes, hours, centimetres and metres must be reconciled."], ["Axis and cumulative errors", "Read the scale and decide whether values are period or running totals."]], ["The fastest check", "Ask whether your answer is sensible in size, direction and unit."]),
    ],
    groups: [
      { id: "qr-topics", label: "Calculation skills", icon: "QR", topics: [
        T("percentages-change", "Percentages & Change", "Handle percentage amounts, change, reverse percentages and repeated changes.", "Look for percent of, increased by, reduced by, original price or percentage-point wording.", ["Use change/original × 100 for percentage change.", "Use multipliers for repeated changes.", "Reverse a percentage by dividing by the multiplier.", "Equal percentage rises and falls do not cancel."], ["Name original, change and final.", "Choose a multiplier or formula.", "Estimate the direction.", "Calculate without early rounding.", "Check the base."], ["Wrong denominator", "Adding successive percentages", "Confusing markup and margin"], ["See it in action", "After a 15% discount, £68 represents 85% of the original price. £68 ÷ 0.85 = £80."]),
        T("ratio-rates", "Ratio, Proportion & Rates", "Share, scale and compare quantities while preserving units.", "Look for ratio, per, speed, cost per unit, work rate, direct proportion or inverse proportion.", ["Add ratio parts before sharing.", "Keep the stated order.", "Direct proportion has a constant multiplier; inverse proportion has a constant product.", "Average rates need actual amounts and times."], ["Write the ratio with labels.", "Find one part or one unit.", "Scale to the target.", "Write the unit equation.", "Sense-check the result."], ["Reversed ratio", "Averaging rates directly", "Minutes-hours mistakes"], ["See it in action", "For a 3:5 split of 96, there are 8 parts, each worth 12, so the shares are 36 and 60."]),
        T("tables-data", "Tables & Data Extraction", "Pull the right figures from dense tables before calculating.", "The display has several headings, years, groups or totals and the question targets a specific combination.", ["Titles and units matter.", "Footnotes can change which values are valid.", "Totals may already include the components shown."], ["Read the question first.", "Trace the exact row and column.", "Copy values with labels.", "Check exclusions and units.", "Only then calculate."], ["Neighbouring cell", "Wrong year", "Double-counting a total"], ["See it in action", "An annual total for one hospital uses its four quarterly cells—not every hospital in those columns."]),
        T("charts-graphs", "Charts & Graphs", "Read scale, series and trends accurately.", "The question uses bars, lines, stacked values, cumulative totals or two axes.", ["Check title, legend, axes and baseline.", "Use the correct series and unit.", "A cumulative June value includes earlier months."], ["Identify x, y and series.", "Read the scale interval.", "Extract the value carefully.", "Convert period or segment values if needed.", "Compare on a common basis."], ["Truncated axis", "Dual-axis swap", "Reading a stacked segment as the total"], ["See it in action", "June activity from a cumulative graph equals cumulative June minus cumulative May."]),
        T("averages-finance", "Averages & Financial Reasoning", "Rebuild totals and track the order of financial operations.", "Look for means, weighted averages, budgets, profit, tax, discounts, interest, margin or break-even.", ["Mean × count reconstructs a total.", "Combined means must be weighted.", "Profit is revenue minus cost.", "Margin uses revenue; markup uses cost."], ["Write the target quantity.", "Reconstruct totals if needed.", "Apply fees, discounts and tax in the stated order.", "Round money at the end."], ["Simple mean of unequal groups", "Margin-markup confusion", "Ignoring fixed costs"], ["See it in action", "20 people averaging 12 and 30 averaging 18 give (20×12 + 30×18) ÷ 50 = 15.6, not 15."]),
        T("units-time", "Units, Time & Measurement", "Convert measurements and apply perimeter, area, volume or time rules.", "The numbers use mixed units, dates, times, scale drawings or geometric dimensions.", ["Convert before combining.", "Square area conversions and cube volume conversions.", "Time uses 60 minutes per hour.", "Check radius versus diameter."], ["Choose the target unit.", "Write conversion factors.", "Apply the correct formula.", "Handle boundaries such as midnight.", "Round to the requested precision."], ["Linear conversion used for area", "Decimal-hour errors", "Radius and diameter mix-up"], ["See it in action", "A 2.4 m by 75 cm rectangle is 2.4 m by 0.75 m, so its area is 1.8 m²."]),
      ]},
    ],
  },
  sjt: {
    short: "SJT", label: "Situational Judgement", color: "#FF6B5C", deep: "#D94B3E", tint: "#FFEDEA",
    tagline: "Choose safe, honest and proportionate professional responses.",
    stats: [["69", "questions"], ["26 min", "section time"], ["2", "response scales"], ["10", "topic guides"]],
    foundations: [
      F("what-sjt-tests", "What SJT is really testing", "Professional judgement, not personal preference.", "SJT asks you to recognise the main professional issue and judge the exact option in front of you. You should not imagine extra facts or mark an acceptable action down simply because it does not solve everything.", [["Safety", "Act quickly enough when a patient or member of the public may be at risk."], ["Honesty", "Correct mistakes, avoid concealment and communicate truthfully."], ["Autonomy and privacy", "Respect informed choices and protect confidential information."], ["Teamwork", "Support colleagues, but do not let loyalty hide serious or repeated concerns."], ["Competence and fairness", "Stay within your role, seek help and treat people with respect."]], ["The main question", "What does a safe, honest and proportionate response look like here?"]),
      F("sjt-format", "Format and scoring", "Use the right scale for the question you have been asked.", "Scenarios usually have several questions attached. Judge each option independently. Partial credit is available, so getting the broad direction right still matters.", [["Importance questions", "Very important / Important / Of minor importance / Not important at all."], ["Appropriateness questions", "Very appropriate / Appropriate but not ideal / Inappropriate but not awful / Very inappropriate."], ["Choose the half first", "Decide important or not, appropriate or inappropriate, then choose the strength."], ["No imagined motives", "Judge the described facts and action, not the intention you invent for someone."]], ["Keep moving", "With roughly 23 seconds per question, use principles rather than writing a long story in your head."]),
      F("professional-principles", "Professional principles", "The ideas that should anchor your decisions.", "You do not need to memorise a script for every scenario. A small set of principles helps you reason through unfamiliar situations.", [["Safety first", "Immediate serious risk comes before convenience, embarrassment or routine admin."], ["Be open and honest", "Do not conceal errors, mislead people or offer false reassurance."], ["Respect choice", "Consent should be informed, voluntary and specific."], ["Protect confidentiality", "Share only when justified and only with people who need the information."], ["Stay within competence", "Get supervision rather than bluffing or abandoning the person."], ["Escalate proportionately", "Minor one-off concerns may need a private word; serious or repeated risks need formal help."]], ["Friendship is not a principle", "Loyalty never outweighs a serious safety or honesty concern."]),
      F("safety-escalation", "Safety and escalation", "Match the urgency of your response to the risk.", "Escalation is not automatically good or bad. The right response depends on how immediate, serious, well-evidenced and repeated the concern is.", [["Immediate danger", "Act to make the situation safe first, then involve the right senior person."], ["Serious but not immediate", "Gather enough accurate information and report through the proper route."], ["Minor one-off lapse", "A calm private conversation may be the best first step."], ["Repeated behaviour", "Escalate when informal steps have failed or the pattern itself creates risk."], ["Need-to-know sharing", "Keep disclosures limited to the people who can help."]], ["Lowest adequate step", "Use the least intrusive action that still protects people properly."]),
      F("proportionality", "Proportionality", "Separate good, imperfect, unhelpful and seriously harmful actions.", "SJT is not only about spotting the perfect response. It also tests whether you can recognise an action that is helpful but incomplete, or unhelpful without being severely wrong.", [["Very appropriate", "Directly handles the main issue, fits the role and is timely."], ["Appropriate but not ideal", "Helpful and acceptable, but incomplete, delayed or indirect."], ["Inappropriate but not awful", "Unhelpful or insufficient, but unlikely to create major harm."], ["Very inappropriate", "Creates serious risk, dishonesty, coercion, privacy breach or concealment."], ["Importance levels", "Ask whether the factor should materially change the professional response."]], ["Do not overcorrect", "The highest escalation is not always the most professional response."]),
      F("sjt-traps", "Common SJT traps", "The instincts that pull an answer away from professional judgement.", "A tempting option often sounds kind, loyal, decisive or rule-following, but misses the main risk or responds at the wrong level.", [["Perfect-answer trap", "An acceptable action can still be appropriate even if it is not the complete plan."], ["Added facts", "Do not invent motives, diagnoses or consequences."], ["Friendship and reciprocity", "Personal loyalty does not reduce a professional duty."], ["Public confrontation", "Private discussion is usually better for a minor issue when safety allows."], ["Escalation extremes", "Do not ignore serious concerns or report every small lapse formally."], ["Confidentiality as absolute", "Safety can justify limited, need-to-know disclosure."], ["Outcome bias", "A risky action is not acceptable just because no harm happened this time."]], ["Judge the action itself", "Good intentions do not rescue a harmful method."]),
    ],
    groups: [
      { id: "sjt-formats", label: "Question formats", icon: "Q", topics: [
        T("importance-questions", "Importance Questions", "Decide how much a factor should influence the response.", "The stem asks how important a consideration is rather than whether an action is good.", ["Safety, rights, honesty and competence are usually highly relevant.", "Embarrassment, convenience and fear of discipline are usually low relevance.", "True details are not automatically important."], ["Name the professional decision.", "Ask whether changing the factor would alter the response.", "Choose important or not important.", "Then judge how decisive it is."], ["Rating vivid emotion too highly", "Treating every true detail as decisive", "Letting friendship influence duty"], ["See it in action", "A friend's fear of disciplinary action should carry little or no weight when deciding whether to raise a serious safety concern."]),
        T("appropriate-action", "Appropriateness Questions", "Judge the quality of one proposed response.", "The stem presents an action and asks where it sits on the appropriateness scale.", ["Judge only the action described.", "An acceptable step does not need to solve everything.", "Check safety, role, timing, directness and proportionality."], ["Identify the main issue.", "Decide appropriate or inappropriate.", "Ask what limits or worsens the action.", "Choose the strength of the rating."], ["Penalising a brief but valid action", "Letting good intent excuse harm", "Assuming the action replaces every other step"], ["See it in action", "Privately asking a colleague about a minor lapse may be appropriate; publicly accusing them without checking facts is likely inappropriate."]),
        T("most-least-questions", "Most & Least Appropriate", "Choose the best and worst action from three plausible options — you must select both.", "Three actions are given, all credible. You pick the most appropriate and the least appropriate. The middle option is implicitly the second-best and is never selected.", ["You must choose two answers: most and least.", "All three options are plausible — none are obviously absurd.", "Compare what each action actually achieves, not just how it sounds.", "The most appropriate action is usually direct, within role and addresses the real issue.", "The least appropriate usually causes harm, breaches something or ignores the problem entirely."], ["Read the scenario and name the core issue.", "Evaluate each option for what it actually achieves.", "Identify which action directly and proportionately addresses the issue — that is your most appropriate.", "Identify which action causes harm, involves dishonesty or completely avoids the problem — that is your least appropriate.", "The middle option is what remains."], ["Choosing the most assertive option automatically as most appropriate", "Choosing the most passive option automatically as least appropriate", "Comparing options against an imaginary perfect response that is not in the list", "Picking based on tone rather than consequences"], ["See it in action", "If option A raises a concern directly, B leaves without saying anything, and C photographs confidential information as evidence — A is most appropriate, C is least appropriate (it creates a new breach), and B is implicitly in the middle."]),
      ]},
      { id: "sjt-themes", label: "Professional themes", icon: "SJT", topics: [
        T("safety-escalation-theme", "Safety & Escalation", "Act at the right speed and through the right route when someone may be at risk.", "Immediate danger, a patient suddenly unwell, a colleague impaired, an error unreported, or signs of possible abuse or neglect.", ["Immediate danger: act to make safe, then call for help.", "Serious or repeated concern: inform an appropriate senior promptly.", "Minor, one-off lapse: a calm private conversation may come first.", "If the first response fails or risk grows: escalate further."], ["Is anyone in immediate danger right now?", "If yes — make safe and get help. Do not pause to investigate first.", "If no — how serious and how well-evidenced is this?", "Take the lowest step that adequately protects people.", "Escalate if it recurs or the first step is ignored."], ["Waiting to avoid embarrassing a colleague while risk continues", "Reporting a minor first mistake directly to the highest authority", "Staying silent because no harm has happened yet", "Conducting your own investigation before reporting"], ["See it in action", "A confused patient is heading towards an unsecured exit. Make them safe and alert staff immediately — that comes before any discussion about how it arose."]),
        T("honesty-records-theme", "Honesty & Accurate Records", "Correct mistakes transparently and communicate truthfully, even when it is uncomfortable.", "An incorrect record, false reassurance, a concealed error, blame without evidence, or pressure to write something untrue.", ["Do not falsify, alter or overwrite records to hide what happened.", "Correct errors through the proper process and leave a clear trail.", "Tell an appropriate supervisor when something has gone wrong.", "Do not offer false reassurance — honest and supportive is not the same as dishonest and kind."], ["What is wrong or misleading?", "Who needs accurate information, and why?", "Correct it through the proper route — not a quiet deletion.", "Involve a supervisor where the error matters to care.", "Acknowledge uncertainty rather than speculating."], ["Secretly overwriting an entry rather than correcting it properly", "Hiding a mistake because no harm occurred this time", "Giving a patient clinical information that is beyond your role to explain", "Blaming someone else before checking the facts"], ["See it in action", "An observation recorded under the wrong patient: correct both records through the proper system, tell the supervising clinician. Do not delete and hope nobody notices."]),
        T("consent-autonomy-theme", "Consent, Autonomy & Confidentiality", "Respect informed choice and share only what is necessary with those who need it.", "A patient refusing, a relative demanding information, a confidential detail shared in public, capacity in question, or pressure on a patient to agree.", ["Consent must be voluntary, informed and specific — silence is not consent.", "A patient with capacity may refuse, even if others disagree.", "Share the minimum necessary information, with the right person, for a legitimate reason.", "Confidentiality is not absolute: serious safety risk can justify proportionate disclosure."], ["What does this person understand and want?", "Is there any pressure, confusion or capacity concern?", "Protect privacy — location, who is present, how much you share.", "If safety and confidentiality conflict, seek senior advice before acting alone."], ["Treating a relative's wishes as automatically overriding the patient's", "Assuming an unwise choice proves lack of capacity", "Sharing the whole record when only one fact is needed", "Using a relative as an interpreter for a sensitive or complex discussion"], ["See it in action", "A patient withdraws consent for student observation mid-examination. Respect it without asking again — they have already said no."]),
        T("communication-theme", "Communication & Compassion", "Listen before deciding, adapt how you communicate, and stay honest even when it feels uncomfortable.", "An upset or frightened patient, a complaint, difficult information to share, a language or disability barrier, or family members speaking over the patient.", ["Listen and let the person explain before you judge the response.", "Adapt language to the person — avoid unexplained clinical terminology.", "Acknowledge distress without promising outcomes you cannot guarantee.", "Speak directly with the patient, not only with relatives or carers present."], ["What is this person actually worried about?", "What do they understand so far?", "What communication support do they need?", "Acknowledge the concern. Find the right person to help if it is beyond your role.", "Do not argue, dismiss or give false reassurance."], ["Dismissing distress because the clinical picture looks minor", "Giving false reassurance to make someone feel better", "Speaking primarily to the relative rather than the patient", "Giving detailed clinical explanations that are beyond your role", "Arguing defensively with someone who has complained"], ["See it in action", "A patient says they did not understand what was explained before their procedure. Acknowledge it and ask the responsible clinician to explain again before continuing — not 'you already signed'."]),
        T("teamwork-theme", "Teamwork & Colleague Concerns", "Support colleagues constructively without covering for unsafe or unacceptable behaviour.", "Poor handover, disrespectful comments, bullying, a colleague struggling or repeatedly late, conflict in a team, or conduct that puts patients at risk.", ["Minor, first-time concerns often begin with a private, respectful conversation.", "Serious impairment, discrimination, repeated behaviour or patient risk needs escalation.", "Report to someone who can act — not to bystanders for solidarity.", "Supporting a colleague does not mean completing dishonest records or hiding serious concerns."], ["Is there immediate patient risk? If yes — protect patients and involve a senior.", "If no — is this minor and first-time, or repeated and serious?", "If minor: a private, factual conversation first.", "If repeated or serious: escalate through an appropriate route.", "Stick to what you observed. Do not diagnose or assume intent."], ["Publicly confronting a colleague over a small first-time lapse", "Staying silent because they are a friend", "Completing dishonest work on their behalf", "Gossiping for support rather than speaking to someone with authority to help", "Prioritising team harmony when a patient is at risk"], ["See it in action", "A student makes repeated mocking comments about a colleague's accent in group teaching. Challenge the comments and report the pattern — it is not something to ignore or wait out."]),
        T("competence-theme", "Competence & Supervision", "Work within your abilities, ask for help when uncertain, and check that those you delegate to can do the task safely.", "Being asked to do something unfamiliar, pressure to attempt without supervision, pretending competence, or unclear instructions.", ["Do not perform a task independently without the required knowledge, training or authority.", "Asking for help is a professional act, not a weakness.", "Before delegating, check the person has the skill, instructions and access to help they need.", "In an emergency: call for the right help and assist within your competence — do not refuse all involvement."], ["Do I have the knowledge, skill and supervision to do this safely?", "If yes: proceed. If no: say so clearly and ask for supervision.", "If delegating: confirm the person understands the task and knows when to escalate.", "In an emergency: get help, then do what you safely can while waiting."], ["Agreeing to a task to avoid appearing unhelpful", "Pretending to understand unclear instructions", "Performing a procedure because another student has done it", "Refusing any help in an emergency because you are 'only a student'", "Delegating without checking whether the person can actually do it"], ["See it in action", "Asked to take blood with only model practice behind you: explain your experience and ask for direct supervision. Attempting it to avoid awkwardness is not the answer."]),
        T("boundaries-theme", "Professional Boundaries & Fairness", "Maintain appropriate professional relationships and act without favouritism or conflicts of interest.", "Gifts, personal or romantic contact with patients, social media boundaries, preferential treatment for friends, discriminatory remarks, or accessing a record without clinical reason.", ["Do not use the professional relationship to gain personal, financial or social advantage.", "Social media: professional standards apply online, including to private accounts.", "Declare and manage conflicts of interest rather than acting on them silently.", "Fairness does not always mean identical treatment — reasonable adjustments may be required."], ["Is there a personal interest, relationship or advantage involved here?", "Does it affect professional judgement or create obligation?", "If yes: declare it or step back.", "Would this treatment differ if the person were not a friend, relative or known to you?", "If yes: that is a fairness problem."], ["Accessing a friend's record out of concern rather than clinical need", "Treating a known patient ahead of others without clinical justification", "Assuming any small gift is automatically a serious breach", "Ignoring discriminatory comments as harmless humour", "Believing a private social media account is professionally separate from your conduct"], ["See it in action", "You recognise a neighbour's name in a clinic list. Do not open their record — you have no clinical reason to. Concern for them is not a legitimate justification."]),
        T("health-wellbeing-theme", "Health, Wellbeing & Fitness to Practise", "Recognise when health may affect safe performance and respond without ignoring the risk or treating illness as misconduct.", "Severe fatigue, contagious illness, medication affecting concentration, a colleague behaving unusually, someone refusing help while clearly struggling, or burnout.", ["The professional issue is how the condition is managed — not the condition itself.", "Safety before presenteeism: continuing when genuinely unsafe is not admirable.", "Seek or encourage independent occupational health advice rather than self-certifying safety.", "In conversation with a struggling colleague: describe what you observed, not a diagnosis."], ["Is anyone currently unsafe? If yes — protect patients and inform a senior.", "If no — speak privately and compassionately. Describe the behaviour you observed.", "Encourage the person to access appropriate support.", "Ensure immediate duties are covered safely.", "Escalate if they refuse help and safety is genuinely at risk."], ["Allowing someone visibly impaired to continue because they insist they are fine", "Sharing private health information with people who do not need it", "Trying to diagnose a colleague rather than describing what you saw", "Offering secrecy when patient safety may require disclosure", "Reporting ordinary stress or a single difficult day as a fitness-to-practise concern"], ["See it in action", "Arriving for placement after almost no sleep and struggling to concentrate: tell the supervisor and discuss whether you can participate safely. Hiding it and hoping is not a professional response."]),
      ]},
    ],
    official: "https://www.gmc-uk.org/education/standards-guidance-and-curricula/guidance/student-professionalism-and-ftp/achieving-good-medical-practice",
  },
};

export const getGuidePages = (section: GuideSection): string[] => [
  "overview",
  ...section.groups.flatMap(g => g.topics.map(t => t.id)),
];

export const findFoundation = (section: GuideSection, pageId: string) =>
  section.foundations.find(p => p.id === pageId);

export const findTopic = (section: GuideSection, pageId: string) =>
  section.groups.flatMap(g => g.topics).find(t => t.id === pageId);

export const getGuidePageTitle = (section: GuideSection, pageId: string): string =>
  pageId === "overview"
    ? `${section.short} study guide`
    : findFoundation(section, pageId)?.title ?? findTopic(section, pageId)?.title ?? "Study guide";
